
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usuariocurso
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rafael123
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: usuariocurso
      MYSQL_ROOT_PASSWORD: rafael123
    ports:
      - "3307:3306"
